apiVersion: v1
kind: Service
metadata:
  name: one-gateway-service-dev
  namespace: one-gateway-dev
spec:
  type: ClusterIP
  selector:
    app: testing-dev-deployment # will change to app deployment in release
  ports:
    - name: http
      port: 3000
      targetPort: 3000
